-- Team: Yu Cai, Dui Lin
LOAD DATA LOCAL INFILE 'items.dat' INTO TABLE Item
FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'sellers.dat' INTO TABLE Seller
FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'bidders.dat' INTO TABLE Bidder
FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'bids.dat' INTO TABLE Bid
FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'categories.dat' INTO TABLE Category
FIELDS TERMINATED BY '|*|';
